// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var details, search;
    search = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movies, _i, _len, _results;
        movies = $.parseJSON(data)['Search'];
        _results = [];
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          _results.push($('.movies').append("<li><a href='#' data-imdb=" + movie.imdbID + ">" + movie.Title + "</a></li>"));
        }
        return _results;
      }).fail(function(j, t, e) {
        return console.log(j, t, e);
      });
    };
    details = function(imdbID) {
      return $.ajax({
        url: "http://www.omdbapi.com/?i=" + imdbID + "&tomatoes=true&plot=full"
      }).done(function(data) {
        var movie;
        movie = $.parseJSON(data);
        console.log(movie);
        $('.movie-title').html(movie.Title);
        $('img.poster').attr('src', movie.Poster);
        return $('.plot').html(movie.Plot);
      }).fail(function(j, t, e) {
        return console.log(j, t, e);
      });
    };
    $('#search').on("submit", function(e) {
      var searchTerm;
      e.preventDefault();
      searchTerm = $('#search input').val();
      return search(searchTerm);
    });
    return $('.search').delegate("li", "click", function(e) {
      var imdbID;
      e.preventDefault();
      imdbID = $(e.target).data('imdb');
      return details(imdbID);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
